### ISSUE TITLE
I alway get errors

### ISSUE THREAD

**Issue by jacklam718** [appshore/meteor-polymer-mobile#1]
Do you know how to solve the error?
my meteor version is 1.0.3.1
Error: UNKNOWN, open '/Users/jack/workspace/meteor-polymer-mobile/public/bower_components/core-shared-lib/demo.html

**Comment by appshore** [comment]
Did you run bower install or bower update before launching meteor? 
It works for me following these stages:
download the git 
meteor update
bower install
meteor

**Comment by jacklam718** [comment]
Yes I have tried bower install and update but also get errors, always get Error: UNKNOWN, 
this time I get the error message
Error: UNKNOWN, open '/Users/jack/workspace/meteor-polymer-mobile/public/bower_components/core-elements/.bower.json'

**Comment by appshore** [comment]
May be you have some issue with bower on your platform? I run on Mac.

Did you modify the source code? did you try with a fresh downloaded git?

Remove the folder public then run meteor. The example shall run at localhost:3000 but without polymer components it will fallback to basic html and the display will be garbled. If it is working then try again with your bower install.

**Comment by jacklam718** [comment]
I has find out the reason,  caused this error because the meteor version my meteor version is 1.0.3.1
I tried to version 1.0 and then is no problem.

**Comment by jacklam718** [comment]
The strange thing is I tried the origin version 1.0.2.1 of this app also I has get same error, but you have no problem.

**Comment by appshore** [comment]
My Meteor is 1.0.3.1 and it is working.
Is that an error during the building time or runtime? What browser are you using?

**Comment by appshore** [comment]
I updated the source code because an icon (drawer) has been removed from the Polymer packages. May be this was the cause of your issue.
